name: Publish Package

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Corepack
        run: corepack enable
        
      - name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn
        
      - name: Build
        run: yarn prepub
        
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn config set npmAuthToken "${NPM_AUTH_TOKEN}"
          yarn config set npmPublishRegistry "https://registry.npmjs.org"
          yarn publish
